# Numpy-Numerical phython lib

In [100]:
import numpy as np
print(np.__version__)

1.18.1


In [110]:
arr = np.ones((3,3),dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [121]:
arr=np.arange(10,1,-1)
arr[arr%2!=0]=-1
arr

array([10, -1,  8, -1,  6, -1,  4, -1,  2])

In [124]:
copy=arr.copy()
copy[0]=1000
print(arr)
print(copy)

[10 -1  8 -1  6 -1  4 -1  2]
[1000   -1    8   -1    6   -1    4   -1    2]


In [143]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

clubbed=np.concatenate([a,b],axis=1)
clubbed

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [152]:
a = np.array([1,2,3])
b=np.repeat(a[0],3)
c=np.repeat(a[1],3)
d=np.tile(a,3)
final=np.concatenate((b,c,d))
final


array([1, 1, 1, 2, 2, 2, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [169]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
final=np.intersect1d(a,b)
final

array([2, 4])

In [189]:
first=np.arange(10)
second=np.arange(15)
new=first.shape
new

(10,)

In [190]:
#Applying a fn to a object of list type
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [206]:
#Swap rows, columns
arr = np.arange(9).reshape(3,3)
#arr[:, [1,2,0]]
#arr
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [212]:
ar=np.random.uniform(5,10,(5,3))
ar

array([[7.70805536, 5.40257595, 5.45981244],
       [5.73052659, 7.56917472, 8.65905408],
       [7.17243096, 8.26963391, 9.00742344],
       [8.47912838, 5.95831226, 9.00004141],
       [6.83251686, 7.30877391, 7.13292054]])

In [217]:
np.std(arr)

2.581988897471611

In [220]:
np.isnan(arr)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [222]:
# Input
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a, a_min=10, a_max=30)

array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

In [236]:
#Sorting methodologies
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[a.argsort()][-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

In [239]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
np.unique(arr,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 7,  7, 10,  5,  6,  6,  2,  6,  7,  4], dtype=int64))

In [246]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays
[a for arr in array_of_arrays for a in arr]# Nested For loop

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [252]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)
a.argsort().argsort()

Array:  [ 9  4 15  0 17 16 17  8  9  0]


array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1], dtype=int64)

In [257]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
print("max",np.amax(a,axis=1))
print("Min",np.apply_along_axis(np.min, arr=a, axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
max [9 8 6 3 9]
Min [4 1 3 3 1]


In [264]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)
out=np.unique(a,return_index=True)[1]
new=np.full(a.shape,True)
new[out]=False
new

[0 0 3 0 2 4 2 2 2 2]


array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [278]:
my=np.array([1,2,3,np.nan,5,6,7,np.nan])
np.isnan(my)
my[~np.isnan(my)]

array([1., 2., 3., 5., 6., 7.])

In [283]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
c= np.concatenate((a,b),axis=1)
c

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [291]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(x==1)[0:4]

(array([ 0,  2,  3,  7,  8, 10, 11], dtype=int64),)

In [294]:
from datetime import datetime
dt64 = np.datetime64('2018-02-25 22:10:10')
dt64.tolist()


datetime.datetime(2018, 2, 25, 22, 10, 10)

In [300]:
np.random.seed(45)
z=np.random.randint(10,size=10)
y=np.arange(5,10,3)
y

array([5, 8])

In [305]:
x = np.array([1,1,2,2,2,4,4,5,6,6,6])
count,bins=np.histogram(x,[0,2,4,6,8])
print("count", count)
print("bins",bins)

count [2 3 3 3]
bins [0 2 4 6 8]


In [309]:
new=np.array([1,2,3,"new"])
new

array(['1', '2', '3', 'new'], dtype='<U11')

# Pandas- Works on series and dataframes

In [311]:
import pandas as pd
pd.__version__

'1.0.1'

In [312]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [324]:
my_series=pd.Series(mydict)
my_series.head()#gives top 5 entries

a    0
b    1
c    2
e    3
d    4
dtype: int64

In [336]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df=pd.DataFrame({'col1':ser1,'col2':ser2})
df.index

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [354]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[ser1.isin(ser2)]

3    4
4    5
dtype: int64

In [364]:
#No of unique items in series
np.random.seed(101)
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()


h    6
f    5
a    5
e    4
d    4
b    3
g    2
c    1
dtype: int64

In [376]:
ser = pd.Series(np.random.randint(1, 10, 7))
ser[ser%3==0].index

Int64Index([2, 5, 6], dtype='int64')

In [381]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [388]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
ser1.append(ser2)#vertical stack
df=pd.concat([ser1,ser2],axis=1)
df

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [405]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
[np.where(i==ser1)[0].tolist()[0] for i in ser2] #pos of Ser1 in ser2


4

In [419]:
#Change 1st letter to caps
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser=ser.map(lambda x: x.title())
ser

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [424]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))
#ser

0    3
1    2
2    4
3    4
dtype: int64

In [426]:
#String of dates to timeseries
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [442]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
mylist=[]
for i in ser:
    count=0
    for j in list("aeiou"):
        if (j in i.lower()):
            count+=1
    if count>=2:
        mylist.append(i)

print("Words withmore than 2 vowels",mylist)
        

Words withmore than 2 vowels ['Apple', 'Orange', 'Money']


In [443]:
#filter emails with given pattern
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
import re
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [449]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
print(weights.groupby(fruit).mean())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['apple', 'carrot', 'banana', 'carrot', 'carrot', 'carrot', 'carrot', 'carrot', 'apple', 'banana']
apple     5.000000
banana    6.500000
carrot    5.333333
dtype: float64


In [456]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
np.sign(np.diff(ser))

array([ 1, -1,  1,  1,  1, -1,  1, -1], dtype=int64)

In [458]:
my_str = 'dbc deb abed gade'
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
least_freq

d    4
e    3
     3
b    3
a    2
g    1
c    1
dtype: int64


'c'

In [501]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
print(df)
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')
df1

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [525]:
np.random.seed(101)
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df)
df["a"].argsort()[::-1][5]
#sorted(df.a)[4]

    a   b   c
0  12  18   7
1  24  12  16
2  10  14   9
3   5   9  22
4  29  29   1
5  15   6  13
6   9  18  20
7  16  27   9
8  20  20  28
9   3  13   9


5

In [550]:
ser = pd.Series(np.random.randint(1, 100, 15))
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
#np.where(ser > ser.mean())[1]


ser:  [52, 50, 75, 83, 38, 54, 94, 74, 6, 38, 57, 36, 16, 41, 43] mean:  50


In [609]:
np.random.seed(101)
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rowsums=df.apply(np.sum,axis=1)
print(df)
df.iloc[np.where((rowsums > 100))[0][-2:],:]

     0   1   2   3
0   21  27  16  33
1   39  21  25  19
2   23  18  14  18
3   31  38  38  10
4   24  15  22  39
5   18  27  29  25
6   36  18  29  39
7   29  37  12  22
8   18  35  29  20
9   22  21  33  10
10  19  33  19  25
11  18  14  29  13
12  38  17  20  30
13  34  17  16  24
14  19  30  28  33


0   1   2   3
12  38  17  20  30
14  19  30  28  33

In [614]:
ser = pd.Series(np.logspace(-2, 2, 30))
low, high = ser.quantile([.05, .95])
high

63.876672220183934

In [632]:
np.random.seed(101)
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)
arr=df[df>0].values.flatten()
arr_qualified=arr[~np.isnan(arr)]
n=int(np.floor(arr_qualified.shape[0]**.5))
top_index=np.argsort(arr_qualified)
top_index

    0   1   2   3   4   5   6   7   8   9
0  -9  43 -11  20 -16  43  20  40  44 -15
1  -8  20  29 -12   9  39  14  24  -1 -10
2 -20 -12  42  16   8  43 -13 -10  32  36
3  18  32  -2  -5  24 -20  -8  -3   4  16
4  43  -1  15  10 -10  40   0   7 -12   6
5  26  27  34 -11  25 -18  -2  38  -9 -10
6  15   8 -17  27  -6  49  40  49  31 -14
7  48   3  15  47  37  26 -17  26   9   1
8   1   3   0   7 -15  29  43 -17  36  -6
9  29  32  -7  27  29   4   0  44  32  40


array([49, 50, 51, 42, 21, 60, 28, 27, 52, 14, 35, 48,  8, 25, 10, 34, 43,
       24, 22, 13, 18,  6,  3,  1, 20, 11, 32, 47, 29, 46, 58, 30, 36, 59,
        7, 56, 53, 40, 62, 16, 19, 57, 31, 17, 55, 45, 33,  9, 63, 38, 26,
        4, 12, 54, 23, 15,  2,  0,  5, 61, 44, 41, 39, 37], dtype=int64)

In [638]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
def swap(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

def row_reverse(df):
    df=df.iloc[::-1,:]
    return df

print(swap(df, 1, 2))
print(row_reverse(df))

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24
    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2   5   6   7   8   9
1  10  11  12  13  14
0   0   1   2   3   4


In [644]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
print(df)
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [672]:
min_by_max=df.apply(lambda x: np.min(x)/np.max(x),axis=1)
min_by_max

0    0.000000
1    0.555556
2    0.714286
3    0.789474
4    0.833333
dtype: float64

In [711]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})
print(df)
df_grouped=df.groupby('col1')
df_grouped['col2'].get_group("banana")

     col1      col2  col3
0   apple  0.500980     3
1  banana  0.567407     8
2  orange  0.035167    14
3   apple  0.657121     5
4  banana  0.297273     6
5  orange  0.595611     4
6   apple  0.607810    10
7  banana  0.477120     0
8  orange  0.663480     3


1    0.567407
4    0.297273
7    0.477120
Name: col2, dtype: float64

In [715]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
print(df)
df.groupby("fruit",as_index=False)['price'].mean()

    fruit    rating  price
0   apple  0.645353      9
1  banana  0.480661      9
2  orange  0.924492     14
3   apple  0.693721     11
4  banana  0.770804      3
5  orange  0.306206      3
6   apple  0.707788      0
7  banana  0.254375      7
8  orange  0.979486      0


fruit     price
0   apple  6.666667
1  banana  6.333333
2  orange  5.666667

In [723]:
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
print(df)
np.where(df.fruit1==df.fruit2)

   fruit1  fruit2
0  orange   apple
1  banana   apple
2   apple  orange
3  banana   apple
4  banana  banana
5  orange   apple
6  banana  banana
7  banana   apple
8  orange  orange
9   apple  banana


(array([4, 6, 8], dtype=int64),)

In [724]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
#Lag and lead
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  17  63  26  80     NaN     39.0
1  86  39  66  48    17.0     89.0
2  51  89  64  88    86.0     64.0
3  15  64  15  54    51.0     98.0
4  69  98   8  67    15.0      NaN


In [730]:
#Unique counts of Df
pd.value_counts(df.values.ravel())

64.0    3
15.0    3
89.0    2
39.0    2
86.0    2
51.0    2
17.0    2
98.0    2
88.0    1
54.0    1
8.0     1
48.0    1
66.0    1
69.0    1
80.0    1
26.0    1
63.0    1
67.0    1
dtype: int64

In [742]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)
#Split in to 3 cols
df_out=df.row.str.split(',| \t', expand=True)
header=df_out.iloc[0]
df_out=df_out[1:]
df_out.columns=header
print(df_out.shape)

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka
(4, 2)
